Use picard jar with fixed version

diff --git a/bam2fastq b/bam2fastq
--- a/bam2fastq
+++ b/bam2fastq
@@ -2,8 +2,6 @@
 
 in_bam=$1 && shift
 
-picard_dir="${PICARDDIR}"
-
 ## use 80 percent of available threads and memory
 threads=$( expr "$(grep -c processor /proc/cpuinfo)" \* 8 / 10 )
 
@@ -15,14 +13,14 @@ out_dir="${bam_dirname}/${sample_name}_FASTQ"
 if [[ "${in_bam}" == "-h" || "${in_bam}" == "--help" ]]; then
     echo "-----"
     echo " Usage: $(basename $0) <BAM_FILE>"
-    echo " Using Picard dir ${picard_dir}"
+    echo " Using Picard jar ${PICARD_PATH}"
     echo "-----"
     exit 1
 fi
 
 ## ---------------
 ## sanity checks
-if [[ ! -d "${picard_dir}" ]]; then echo "[ERROR] Picard dir not found (${picard_dir})"; exit 1; fi
+if [[ ! -f "${PICARD_PATH}" ]]; then echo "[ERROR] Picard file not found (${PICARD_PATH})"; exit 1; fi
 if [[ ! -f "${in_bam}" ]]; then echo "[ERROR] Bam file not found (${in_bam})"; exit 1; fi
 if [[ ! -w "$(dirname "${out_dir}")" ]]; then echo "[ERROR] Output dir not writable?"; exit 1; fi
 
@@ -45,8 +43,7 @@ else
 fi
 
 echo "[INFO] Running SamToFastq for bam file: $(basename "${in_bam}")"
-echo "java -Xmx50G -jar ${picard_dir}/picard.jar SamToFastq ODIR=${out_dir} OPRG=true RGT=ID NON_PF=true RC=true I=${in_bam}"
-PicardCommandLine SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${in_bam}"
+java -Xmx50G -jar "${PICARD_PATH}" SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${in_bam}"
 
 echo "[INFO] About to rename fastq files"
 for fastq_path in "${out_dir}"/*fastq; do
diff --git a/cram2bam b/cram2bam
--- a/cram2bam
+++ b/cram2bam
@@ -3,6 +3,7 @@
 if [[ -z "$1" || "$1" == "-h" || "$1" == "--help" ]]; then
     echo "-----"
     echo " Usage: $(basename $0) <CRAM file>"
+    echo " Using samtools at ${SAMTOOLS_PATH}"
     echo "-----"
     exit 1
 fi
@@ -16,7 +17,7 @@ main() {
     info "Starting with $(basename $0)"
     
     ## sanity checks
-    command -v $SAMTOOLS_PATH >/dev/null 2>&1 || die "samtools not found"
+    command -v "${SAMTOOLS_PATH}" >/dev/null 2>&1 || die "samtools not found"
     [[ -f "${cram}" ]] || die "File not found (${cram})"
     [[ "${cram}" =~ cram$ ]] || die "Not a CRAM file (${cram})"
 
@@ -25,15 +26,15 @@ main() {
 
     ## jobs
     info "Converting ${cram} to ${bam} (with samtools view)"
-    $SAMTOOLS_PATH view -O bam -o "${bam}" --threads "${threads}" "${cram}"
+    "${SAMTOOLS_PATH}" view -O bam -o "${bam}" --threads "${threads}" "${cram}"
 
     info "Creating flagstat for ${cram}"
     cram_flagstat="${cram}.flagstat"
-    $SAMTOOLS_PATH flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}"
+    "${SAMTOOLS_PATH}" flagstat --threads "${threads}" "${cram}" > "${cram_flagstat}"
 
     info "Creating flagstat for ${bam}"
     bam_flagstat="${bam}.flagstat"
-    $SAMTOOLS_PATH flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}"
+    "${SAMTOOLS_PATH}" flagstat --threads "${threads}" "${bam}" > "${bam_flagstat}"
 
     total_cram=$(cat ${cram_flagstat} | head -1 | cut -d" " -f1)
     total_bam=$(cat ${bam_flagstat} | head -1 | cut -d" " -f1)
