Add option to sort BAM by read name before converting to FASTQ

diff --git a/cram2fastq b/cram2fastq
--- a/cram2fastq
+++ b/cram2fastq
@@ -4,6 +4,7 @@ gcp_user_project=$1 # optional new sample name
 cram=$2 # can be GCP url or local file
 bucket=$3 # must be the GCP url of a bucket or directory
 new_name=$4 # optional new sample name
+sort_bam=$5 # whether to sort BAM before running SamToFastq
 
 threads=$(($(grep -c processor /proc/cpuinfo) * 8 / 10 ))
 samtools="samtools"
@@ -45,11 +46,9 @@ main() {
 
     if [[ "${cram}" =~ cram$ ]]; then
         convert_cram_to_bam "${cram}" "${bam}" || exit 1
-        info "Deleting local copy of cram"
-        rm "${cram}" || die "Could not delete the local copy of the cram: ${cram}"
     fi
 
-    convert_bam_to_fastq "${bam}" "${fastq_dir}" || exit 1
+    convert_bam_to_fastq "${bam}" "${fastq_dir}" "${sort_bam}" || exit 1
 
     if [[ "${new_name}" != "" ]]; then
         info "Renaming compressed FASTQ files to include provided sample name"
@@ -101,11 +100,15 @@ convert_cram_to_bam() {
 
     info "Running diff on flagstats"
     diff "${cram_flagstat}" "${bam_flagstat}" || die "Flagstat diff failed: check result before using downstream!!"
+
+    info "Deleting local copy of cram"
+    rm "${cram}" || die "Could not delete the local copy of the cram: ${cram}"
 }
 
 convert_bam_to_fastq() {
     local bam=$1 && shift
     local out_dir=$1 && shift
+    local sort_bam=$1 && shift
 
     info "Converting ${bam} to FASTQ"
 
@@ -117,9 +120,24 @@ convert_bam_to_fastq() {
         die "Exiting because renaming of fastq files will probably fail"
     fi
 
-    info "Running SamToFastq for bam file: $(basename "${bam}")"
-    java -Xmx31G -jar "${picard}" SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${bam}" 2>&1 \
+    if [[ "${sort_bam}" == "TRUE" ]]; then
+      info "Sort BAM by read name"
+      bam_to_convert="${bam/.bam/.sorted.bam}"
+      ${samtools} sort -n -@ "${threads}" -o "${bam_to_convert}" "${bam}" || die "Could not sort BAM by read name"
+
+      info "Delete unsorted BAM"
+      rm "${bam}" || die "Could not delete the unsorted BAM: ${bam}"
+    else
+      info "Don't sort BAM by read name"
+      bam_to_convert="${bam}"
+    fi
+
+    info "Running SamToFastq for bam file: $(basename "${bam_to_convert}")"
+    java -Xmx31G -jar "${picard}" SamToFastq ODIR="${out_dir}" OPRG=true RGT=ID NON_PF=true RC=true I="${bam_to_convert}" 2>&1 \
         || die "SamToFastq failed"
+
+    info "Delete BAM"
+    rm "${bam_to_convert}" || die "Could not delete the BAM: ${bam_to_convert}"
 
     info "Renaming FASTQ files to standard format"
     find "${out_dir}" -name "*.fastq" | while read -r fastq_path; do
diff --git a/cram2fastq_k8 b/cram2fastq_k8
--- a/cram2fastq_k8
+++ b/cram2fastq_k8
@@ -1,11 +1,13 @@
 #!/usr/bin/env bash
 
 function printUsage(){
-    echo "USAGE: $0 run <gcp-user-project> <cram-url> <output-bucket> <sample-name>"
+    echo "USAGE: $0 run <gcp-user-project> <cram-url> <output-bucket> <sample-name> <sort-bam>"
     echo "  <gcp-user-project> The GCP user project"
     echo "  <cram-url>         The complete gs url to input CRAM"
     echo "  <output-bucket>    The name of bucket to copy output fastq files to"
     echo "  <sample-name>      The tag that FASTQ filenames will have as start"
+    echo "  <sort-bam>         (Optional) If set to 'TRUE' BAM will be sorted by read name before running SamToFastq."
+    echo "                     This increases runtime but lowers peak memory usage. Value needs to be empty, 'TRUE' or 'FALSE'."
     exit 1
 }
 
@@ -14,6 +16,7 @@ function run() {
     cram_url=$1 && shift
     out_bucket=$1 && shift
     sample_name=$1 && shift
+    sort_bam=$1 && shift
 
     # sanity checks
     if [[ ! "${cram_url}" =~ ^gs[-/:._a-zA-Z0-9]+$ ]]; then
@@ -23,7 +26,10 @@ function run() {
       echo "[ERROR] Output bucket wrong format (can only contain [a-zA-Z0-9] or '-' or '/')" >&2 && exit 1
     fi
     if [[ ! "${sample_name}" =~ ^[-a-zA-Z0-9]+$ ]]; then
-      echo "[ERROR] Sample name (can only contain [a-zA-Z0-9] or '-')" >&2 && exit 1
+      echo "[ERROR] Sample name wrong format (can only contain [a-zA-Z0-9] or '-')" >&2 && exit 1
+    fi
+    if [[ "${sort_bam}" != "" && "${sort_bam}" != "TRUE" && "${sort_bam}" != "FALSE" ]]; then
+      echo "[ERROR] 'sort_bam' variable can only be equal to '', 'TRUE' or 'FALSE'" >&2 && exit 1
     fi
 
     pod_name="$(echo "cram2fq-${sample_name}" | awk '{print tolower($0)}')"
@@ -39,6 +45,7 @@ function run() {
     -e "s/VAR_CRAM_URL/${cram_url_for_sed}/g" \
     -e "s/VAR_OUTPUT_BUCKET/${out_bucket_for_sed}/g" \
     -e "s/VAR_SAMPLE_NAME/${sample_name}/g" \
+    -e "s/VAR_SORT_BAM/${sort_bam}/g" \
     -e "s/VAR_GCP_USER_PROJECT/${gcp_user_project}/g" \
     k8/hmf-crunch/deploy.yaml \
     | kubectl create -f -
