Allow BAM's with non-standard inputs

diff --git a/cram2fastq b/cram2fastq
--- a/cram2fastq
+++ b/cram2fastq
@@ -5,6 +5,7 @@ cram=$2 # can be GCP url or local file
 bucket=$3 # must be the GCP url of a bucket or directory
 new_name=$4 # optional new sample name
 sort_bam=$5 # whether to sort BAM before running SamToFastq
+non_standard_input=$6  # skip fixing FASTQ file name format
 
 threads=$(($(grep -c processor /proc/cpuinfo) * 8 / 10 ))
 samtools="samtools"
@@ -48,7 +49,7 @@ main() {
         convert_cram_to_bam "${cram}" "${bam}" || exit 1
     fi
 
-    convert_bam_to_fastq "${bam}" "${fastq_dir}" "${sort_bam}" || exit 1
+    convert_bam_to_fastq "${bam}" "${fastq_dir}" "${sort_bam}" "${non_standard_input}" || exit 1
 
     if [[ "${new_name}" != "" ]]; then
         info "Renaming compressed FASTQ files to include provided sample name"
@@ -109,15 +110,18 @@ convert_bam_to_fastq() {
     local bam=$1 && shift
     local out_dir=$1 && shift
     local sort_bam=$1 && shift
+    local non_standard_input=$1 && shift
 
     info "Converting ${bam} to FASTQ"
 
     # double check format of RG/ID tags in header
-    unexpected_read_group_count=$(samtools view -H "${bam}" | grep "^@RG" | grep -vcP "_L00[1-8]_" )
-    if [[ "${unexpected_read_group_count}" -gt 0 ]]; then
-        warn "There are RG ID header lines in BAM without the expected pattern present (_L00[1-8]_):"
-        ${samtools} view -H "${bam}" | grep "^@RG"
-        die "Exiting because renaming of fastq files will probably fail"
+    if [[ "${non_standard_input}" != "TRUE" ]]; then
+      unexpected_read_group_count=$(samtools view -H "${bam}" | grep "^@RG" | grep -vcP "_L00[1-8]_" )
+      if [[ "${unexpected_read_group_count}" -gt 0 ]]; then
+          warn "There are RG ID header lines in BAM without the expected pattern present (_L00[1-8]_):"
+          ${samtools} view -H "${bam}" | grep "^@RG"
+          die "Exiting because renaming of fastq files will probably fail"
+      fi
     fi
 
     if [[ "${sort_bam}" == "TRUE" ]]; then
@@ -139,19 +143,21 @@ convert_bam_to_fastq() {
     info "Delete BAM"
     rm "${bam_to_convert}" || die "Could not delete the BAM: ${bam_to_convert}"
 
-    info "Renaming FASTQ files to standard format"
-    find "${out_dir}" -name "*.fastq" | while read -r fastq_path; do
-        old_name=$(basename "${fastq_path}")
-        new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
-        # Fix incorrect fastq names of the forms *_R1_.fastq and *_R2_.fastq
-        new_name="${new_name//"_.fastq"/"_001.fastq"}"
+    if [[ "${non_standard_input}" != "TRUE" ]]; then
+      info "Renaming FASTQ files to standard format"
+      find "${out_dir}" -name "*.fastq" | while read -r fastq_path; do
+          old_name=$(basename "${fastq_path}")
+          new_name=$(echo "${old_name}" | sed 's#\.fastq##g' - | awk 'BEGIN { FS = "_" } ; { print $1"_"$2"_"$3"_"$4"_R"$6"_"$5".fastq" }')
+          # Fix incorrect fastq names of the forms *_R1_.fastq and *_R2_.fastq
+          new_name="${new_name//"_.fastq"/"_001.fastq"}"
 
-        new_path="${out_dir}/${new_name}"
-        if [[ "${fastq_path}" != "${new_path}" ]]; then
-          mv "${fastq_path}" "${new_path}" || die "Could not rename FASTQ file to the proper name: '${fastq_path}' to '${new_name}'"
-          info "  Renamed ${old_name} to ${new_name}"
-        fi
-    done
+          new_path="${out_dir}/${new_name}"
+          if [[ "${fastq_path}" != "${new_path}" ]]; then
+            mv "${fastq_path}" "${new_path}" || die "Could not rename FASTQ file to the proper name: '${fastq_path}' to '${new_name}'"
+            info "  Renamed ${old_name} to ${new_name}"
+          fi
+      done
+    fi
 
     info "Compressing FASTQ files in ${out_dir} (using pigz)"
     find "${out_dir}" -name "*.fastq" -exec pigz {} + || die "Could not compress FASTQ files with pigz"
diff --git a/cram2fastq_k8 b/cram2fastq_k8
--- a/cram2fastq_k8
+++ b/cram2fastq_k8
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 
 function printUsage(){
-    echo "USAGE: $0 run <gcp-user-project> <cram-url> <output-bucket> <sample-name> <sort-bam>"
-    echo "  <gcp-user-project> The GCP user project"
-    echo "  <cram-url>         The complete gs url to input CRAM"
-    echo "  <output-bucket>    The name of bucket to copy output fastq files to"
-    echo "  <sample-name>      The tag that FASTQ filenames will have as start"
-    echo "  <sort-bam>         (Optional) If set to 'TRUE' BAM will be sorted by read name before running SamToFastq."
-    echo "                     This increases runtime but lowers peak memory usage. Value needs to be empty, 'TRUE' or 'FALSE'."
+    echo "USAGE: $0 run <gcp-user-project> <cram-url> <output-bucket> <sample-name> <sort-bam> <non-standard-input>"
+    echo "  <gcp-user-project>    The GCP user project"
+    echo "  <cram-url>            The complete gs url to input CRAM"
+    echo "  <output-bucket>       The name of bucket to copy output fastq files to"
+    echo "  <sample-name>         The tag that FASTQ filenames will have as start"
+    echo "  <sort-bam>            (Optional) If set to 'TRUE' BAM will be sorted by read name before running SamToFastq."
+    echo "                        This increases runtime but lowers peak memory usage. Value needs to be empty, 'TRUE' or 'FALSE'."
+    echo "  <non-standard-input>  (Optional) If set to 'TRUE' skip all checks and FASTQ renaming that expect an input with the standard Hartwig format."
     exit 1
 }
 
@@ -17,6 +18,7 @@ function run() {
     out_bucket=$1 && shift
     sample_name=$1 && shift
     sort_bam=$1 && shift
+    non_standard_input=$1 && shift
 
     # sanity checks
     if [[ ! "${cram_url}" =~ ^gs[-/:._a-zA-Z0-9]+$ ]]; then
@@ -30,6 +32,9 @@ function run() {
     fi
     if [[ "${sort_bam}" != "" && "${sort_bam}" != "TRUE" && "${sort_bam}" != "FALSE" ]]; then
       echo "[ERROR] 'sort_bam' variable can only be equal to '', 'TRUE' or 'FALSE'" >&2 && exit 1
+    fi
+    if [[ "${non_standard_input}" != "" && "${non_standard_input}" != "TRUE" && "${non_standard_input}" != "FALSE" ]]; then
+      echo "[ERROR] 'non_standard_input' variable can only be equal to '', 'TRUE' or 'FALSE'" >&2 && exit 1
     fi
 
     if [[ "${sample_name}" != "" ]]; then
@@ -55,6 +60,7 @@ function run() {
     -e "s/VAR_OUTPUT_BUCKET/${out_bucket_for_sed}/g" \
     -e "s/VAR_SAMPLE_NAME/${sample_name}/g" \
     -e "s/VAR_SORT_BAM/${sort_bam}/g" \
+    -e "s/VAR_NON_STANDARD_INPUT/${non_standard_input}/g" \
     -e "s/VAR_GCP_USER_PROJECT/${gcp_user_project}/g" \
     ${deploy_yaml} \
     | kubectl create -f -
